server:
  port: 8081
spring:
  profiles:
    active: test
  main:
    show-banner: false
  thymeleaf:
    prefix: /WEB-INF/views/
    suffix: .html
liquibase:
  change-log: classpath:/liquibase/changelog.xml
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:mystamps;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialize: false
liquibase:
  contexts: scheme, init-data, test-data
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/mystamps
    username: mystamps
    password: q1
    driver-class-name: com.mysql.jdbc.Driver
    initialize: false
    validation-query: SELECT 1
    test-on-borrow: false
liquibase:
  # see also duplicate definition at pom.xml
  contexts: scheme, init-data, prod-data
