---

# TODO: use systemd module (requires ansible 2.2+)
- name: Reloading systemd service
  command:
    systemctl daemon-reload

- name: Restarting mystamps service
  service:
    name: mystamps
    state: restarted
