apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mystamps
  name: mystamps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mystamps
  template:
    metadata:
      labels:
        app: mystamps
    spec:
      containers:
      - image: phpcoder/mystamps:0.4.2
        name: mystamps
