name: Comparison with Spring Boot dependencies

on:
  push:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpull_requestpull_request_targetbranchesbranches-ignore
    branches:
      - master
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
    paths:
      - pom.xml
      - src/main/scripts/mise.toml
      - src/main/scripts/show-spring-boot-version-diff.sh
      - .github/workflows/dependencies-diff.yml

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  contents: read # for "git clone"

defaults:
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun
  run:
    # Enable fail-fast behavior using set -eo pipefail
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

jobs:
  show-spring-boot-version-diff:
    name: Run show-spring-boot-version-diff.sh
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-22.04
    steps:
      - name: Clone source code
        uses: actions/checkout@v6.0.1 # https://github.com/actions/checkout
        with:
          # Whether to configure the token or SSH key with the local git config. Default: true
          persist-credentials: false

      - name: Install mise to set up spring-boot-dependency-checker
        uses: jdx/mise-action@v3.5.1 # https://github.com/jdx/mise-action
        with:
          version: 2025.11.11                 # [default: latest] mise version to install
          install: true                       # [default: true] run `mise install`
          cache: true                         # [default: true] cache mise using GitHub's cache
          log_level: info                     # [default: info] log level
          working_directory: src/main/scripts # [default: .] directory to run mise in
        env:
          # Workaround: don't install parent's dependencies as we don't use them
          # See: https://github.com/jdx/mise-action/issues/183
          # https://mise.jdx.dev/configuration/settings.html#disable_tools
          MISE_DISABLE_TOOLS: java,maven

      - name: Compare versions
        working-directory: src/main/scripts
        run: ./show-spring-boot-version-diff.sh
